AZURE_OPENAI_API_KEY="D4N7g1LVeUliOfUgaeW5kFGuqaZ90jH94F0rHWlosDF6QW59yY27JQQJ99BBACHYHv6XJ3w3AAAAACOGr5Mm"
AZURE_OPENAI_ENDPOINT="https://medicalaidevhu3914420087.openai.azure.com/"
AZURE_OPENAI_DEPLOYMENT="o1-mini"
AZURE_OPENAI_API_VERSION="2024-08-01-preview"
TAVILY_API_KEY="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"